### ISSUE TITLE
Not working on MacOS Sequoia

### ISSUE THREAD

**Issue by DrKoneko** [3v0k4/dextop#1]
When I open the app on Mac OS Sequoia it immediately closes. It was working fine yesterday before updating so I assume something in the new Mac OS version broke something. Let me know what information you need, I'm not really sure how to debug apps on Mac OS. Sorry!

Thanks for the amazing work you do!

**Comment by 3v0k4** [comment]
Thanks for the good words.

Yes, it looks like Electron had [some issues with Sequoia](https://github.com/heyman/heynote/issues/232). But it seems newer versions of Electron would [work fine](https://github.com/heyman/heynote/issues/232#issuecomment-2205315917).

I'm not currently enrolled in the [Apple Developer Program](https://developer.apple.com/programs/), so I cannot release a new version of DexTop at the moment because I don't have the certificates to sign the app.

I could update the dependencies and share with you the few steps needed to build the application directly on your machine. That would also help me confirm DexTop works on Sequoia.

Would you be willing to do that?

**Comment by DrKoneko** [comment]
Sorry I didn't get back to you earlier, I'd absolutely be willing to do that.

**Comment by 3v0k4** [comment]
I upgraded the dependencies on `main`.

What you need to do to run the app is:

```
git clone git@github.com:3v0k4/dextop.git
cd dextop
npm install
npm run start
```

To use `npm` you need node installed. You can check it with:

```
node --version
```

On my laptop, I'm running v18.19.0 but later versions would work too.

Please let me know how that goes 🙏

**Comment by DrKoneko** [comment]
When I tried cloning the repo it failed, however when I used `git clone https://github.com/3v0k4/dextop.git` it cloned fine. I ran with npm and it started and worked flawlessly. In the terminal there is are a bunch of errors that all seem the same:
`lQueryDeviceAttribEXT: Bad attribute.
[4577:1007/141359.961803:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.
[4577:1007/141400.010695:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.
[4577:1007/141400.060079:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.
[4577:1007/141400.109655:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.
[4577:1007/141400.161671:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.
[4577:1007/141400.177945:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.
[4577:1007/141400.227416:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.
[4577:1007/141400.246255:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.
[4577:1007/141400.269155:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.
[4577:1007/141400.284139:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.` (This is only a fraction of the errors but they're all the same with different numbers.)
They only appear when the dextop window is open, but it doesn't seem to have an effect on anything. My BG is showing the same as it does on my phone.

**Comment by 3v0k4** [comment]
Thanks for reporting DexTop works fine on Sequoia with the code from `main`.

As I said before, I cannot release a new version at the moment, so there are a couple of options:

You can run it with `npm run start` as you already did, but I expect that could be annoying as you need to keep the terminal around.

~~The alternative would be to run `npm run package`, which would create `/path/to/repo/out/DexTop-darwin-x64/DexTop.app` (the path inside `out/` could be slightly different depending on your OS). Then, you can move the `DexTop.app` wherever you want and use it as a normal app.~~

The alternative would be to run `npm run make`, which would create `/path/to/repo/out/make/`. Then, you can use the installer inside `make/`.

You'll get a warning when you run the app that says something like "Error: Could not get code signature for running application"—it's connected to the the fact the application is not signed as I shared in a previous comment.

EDIT: use `npm run make` (instead of `npm run package`)

**Comment by DrKoneko** [comment]
I tried running `npm run make` but it resulted in an error:
Jakobys-MacBook-Pro:dextop jakoby$ npm run make

> dextop@0.11.0 make
> electron-forge make

✔ Checking your system
✔ Loading configuration
✔ Resolving make targets
  › Making for the following targets:
✔ Running package command
  ✔ Preparing to package application
  ✔ Running packaging hooks
    ✔ Running generateAssets hook
    ✔ Running prePackage hook
      ✔ [plugin-webpack] Preparing webpack bundles
        ✔ Preparing native dependencies [0.4s]
        ✔ Building webpack bundles [3s]
  ✔ Packaging application
    ✔ Packaging for x64 on darwin [1s]
  ✔ Running postPackage hook
✔ Running preMake hook
❯ Making distributables
  ✖ Making a dmg distributable for darwin/x64
    › Cannot find module 'appdmg'
      Require stack:
      - /Users/jakoby/dextop/node_modules/electron-installer-dmg/dist/index.js
      - /Users/jakoby/dextop/node_modules/@electron-forge/maker-dmg/dist/MakerDM
      G.js
      - /Users/jakoby/dextop/node_modules/@electron-forge/core/helper/dynamic-im
      port.js
      - /Users/jakoby/dextop/node_modules/@electron-forge/core/dist/util/forge-c
      onfig.js
      -
      /Users/jakoby/dextop/node_modules/@electron-forge/core/dist/util/index.js
      - /Users/jakoby/dextop/node_modules/@electron-forge/core/dist/api/index.js
      - /Users/jakoby/dextop/node_modules/@electron-forge/cli/dist/electron-forg
      e-make.js
◼ Running postMake hook

(node:1270) [DEP0174] DeprecationWarning: Calling promisify on a function that returns a Promise is likely a mistake.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:1270) [DEP0174] DeprecationWarning: Calling promisify on a function that returns a Promise is likely a mistake.
(node:1270) [DEP0174] DeprecationWarning: Calling promisify on a function that returns a Promise is likely a mistake.
(node:1270) [DEP0174] DeprecationWarning: Calling promisify on a function that returns a Promise is likely a mistake.
(node:1270) [DEP0174] DeprecationWarning: Calling promisify on a function that returns a Promise is likely a mistake.
(node:1270) [DEP0174] DeprecationWarning: Calling promisify on a function that returns a Promise is likely a mistake.
(node:1270) [DEP0174] DeprecationWarning: Calling promisify on a function that returns a Promise is likely a mistake.
(node:1270) [DEP0174] DeprecationWarning: Calling promisify on a function that returns a Promise is likely a mistake.
(node:1270) [DEP0174] DeprecationWarning: Calling promisify on a function that returns a Promise is likely a mistake.
(node:1270) [DEP0174] DeprecationWarning: Calling promisify on a function that returns a Promise is likely a mistake.
(node:1270) [DEP0174] DeprecationWarning: Calling promisify on a function that returns a Promise is likely a mistake.
(node:1270) [DEP0174] DeprecationWarning: Calling promisify on a function that returns a Promise is likely a mistake.
(node:1270) [DEP0174] DeprecationWarning: Calling promisify on a function that returns a Promise is likely a mistake.

An unhandled rejection has occurred inside Forge:
Error: Cannot find module 'appdmg'
Require stack:
- /Users/jakoby/dextop/node_modules/electron-installer-dmg/dist/index.js
- /Users/jakoby/dextop/node_modules/@electron-forge/maker-dmg/dist/MakerDMG.js
- /Users/jakoby/dextop/node_modules/@electron-forge/core/helper/dynamic-import.js
- /Users/jakoby/dextop/node_modules/@electron-forge/core/dist/util/forge-config.js
- /Users/jakoby/dextop/node_modules/@electron-forge/core/dist/util/index.js
- /Users/jakoby/dextop/node_modules/@electron-forge/core/dist/api/index.js
- /Users/jakoby/dextop/node_modules/@electron-forge/cli/dist/electron-forge-make.js
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1248:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/jakoby/dextop/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:1074:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1339:12)
    at require (node:internal/modules/helpers:135:16)
    at build (/Users/jakoby/dextop/node_modules/electron-installer-dmg/src/index.ts:98:37)
    at createDMG (/Users/jakoby/dextop/node_modules/electron-installer-dmg/src/index.ts:208:10)
    at async MakerDMG.make (/Users/jakoby/dextop/node_modules/@electron-forge/maker-dmg/src/MakerDMG.ts:32:5)
    at async /Users/jakoby/dextop/node_modules/@electron-forge/core/src/api/make.ts:280:41
    at async _Task.taskFn (/Users/jakoby/dextop/node_modules/@electron-forge/tracer/src/index.ts:51:14)
    at async _Task.run (/Users/jakoby/dextop/node_modules/listr2/dist/index.cjs:2063:11)

**Comment by 3v0k4** [comment]
It looks like `package` succeeds (`make` runs first `package`), but `make` fails when creating the DMG.

If `package` actually succeeded, you should find the DexTop.app file somewhere inside `out/` and you could use that.

Otherwise, do you have `brew` available? Could you try the following([source](https://github.com/electron/forge/issues/3371#issuecomment-2281115374)):

```
brew install python-setuptools
npm run make
```

**Comment by DrKoneko** [comment]
Unfortunately I still get the same error. I verified that python-setuptools was installed. I also installed python 3.13 but it still doesn't change anything.

**Comment by 3v0k4** [comment]
Does `npm run package` succeed?

Could you find the `DexTop.app` inside `out/`?

**Comment by DrKoneko** [comment]
Yes, I'm not sure when it was created but the app suddenly appeared upon running the command again. It still failed but unlike this morning it finally did reappear. Thank you so much!
